module.exports = {
  testEnvironment: 'node',
  coverageDirectory: 'coverage',
  collectCoverageFrom: [
    '*.js',
    'logger/**/*.js',
    '!node_modules/**',
    '!coverage/**',
    '!dist/**',
    '!logs/**',
    '!jest.config.js',
    '!__tests__/**',
  ],
  coveragePathIgnorePatterns: ['/node_modules/', '/coverage/', '/dist/', '/logs/'],
  testMatch: ['**/__tests__/**/*.test.js', '**/?(*.)+(spec|test).js'],
  testPathIgnorePatterns: ['/node_modules/', '/__tests__/setup.js'],
  setupFilesAfterEnv: ['./__tests__/setup.js'],
  verbose: true,
  clearMocks: true,
  resetMocks: true,
  restoreMocks: true,
};
